server:
  servletPath: /

spring:
  application:
    name: eureka_server_integration
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  server:
    # 关闭自我保护机制，保证不可用的服务被及时剔除
    enable-self-preservation: false
  instance:
    hostname: localhost
    #服务失效的时间，默认为90秒。
    eureka.instance.lease-expiration-duration-in-seconds: 120
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log4j2.xml



---
server:
  port: 8761
spring:
  config:
    activate:
      on-profile: server1
---
server:
  port: 8762

spring:
  config:
    activate:
      on-profile: server2